name: Update Hash

on:
  workflow_dispatch:
    inputs:
      music:
        default: false
        required: true
        type: boolean
      jacket:
        default: false
        required: true
        type: boolean
      preview:
        default: false
        required: true
        type: boolean

env:
  music: ${{ inputs.music }}
  jacket: ${{ inputs.jacket }}
  preview: ${{ inputs.preview }}

jobs:
  update:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
          
      - name: Install dependencies
        run: npm install
        
      - name: Update Hash
        run: node update.js ${{ env.music == 'true' && 'music' || '' }} ${{ env.jacket == 'true' && 'jacket' || '' }} ${{ env.preview == 'true' && 'preview' || '' }}
      
      - name: Commit report
        run: |
          git config --global user.name 'gorenganhunter'
          git config --global user.email 'gorengandev@gmail.com'
          git commit -m "Update Hash"
          git push
